In [1]:
import numpy as np
y_predicted = np.array([1,1,0,0,1])
y_true = np.array([0.30,0.7,1,0,0.5])

In [2]:
#Implement Mean Absolute Error

In [3]:
def mae(y_predicted, y_true):
    total_error = 0
    for yp, yt in zip(y_predicted, y_true):
        total_error += abs(yp - yt)
    print("Total error is:",total_error)
    mae = total_error/len(y_predicted)
    print("Mean absolute error is:",mae)
    return mae

In [4]:
mae(y_predicted, y_true)

Total error is: 2.5
Mean absolute error is: 0.5


np.float64(0.5)

In [8]:
np.mean(np.abs(y_predicted-y_true))

np.float64(0.5)

In [6]:
np.abs(y_predicted-y_true)

array([0.7, 0.3, 1. , 0. , 0.5])

In [7]:
def mae_np(y_predicted, y_true):
    return np.mean(np.abs(y_predicted-y_true))
mae_np(y_predicted, y_true)

np.float64(0.5)

In [9]:
#Implement Log Loss or Binary Cross Entropy

In [10]:
epsilon = 1e-15
np.log([1e-15])

array([-34.53877639])

In [11]:
y_predicted

array([1, 1, 0, 0, 1])